baseURL = 'https://musical.studio/'
languageCode = 'fr'
title = 'Musical.Studio'
theme = "mediumish-gohugo-theme"
summaryLength = 25
contentDir = "content"
copyright = "Gilles Chehade - All rights reserved"
disqusShortname = "musical-studio"
googleAnalytics = "G-1F6307Z0H3"
enableEmoji = true

[permalinks]
	posts = "/posts/:year-:month-:day/:slug"

[markup.goldmark.renderer]
  unsafe = true

[params]
  logo = "/images/logo.png"
  description = "La MAO pour les noobs."
  #mailchimp = "you can provide a mailchimp-link here, see below"
  #mailprotect = "you can provide a protector-name here, see below"
  #customCSS = ["css/tweaks.css", "css/customHeader.css"]

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]
	page = ["HTML"]


[params.author]
  name = "Gilles Chehade"
  thumbnail = "/images/gilles-chehade.jpeg"
  description = "Createur du blog."


[params.index]
  picture = "/images/logo.png"
  title = "musical.studio"
  subtitle = "La MAO pour les noobs."
  mdtext = '''<a href="/posts/">Entrer dans le blog</a>'''
  alertbar = true


[[menu.main]]
    name = "Mentions légales"
    url = "/mentions/"
    weight = 1

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"