baseURL = 'https://musical.studio'
languageCode = 'fr'
title = 'Musical.Studio'
theme = "mediumish-gohugo-theme"
summaryLength = 25
contentDir = "content"
copyright = "Gilles Chehade - All rights reserved"
disqusShortname = "musical-studio"
googleAnalytics = "G-1F6307Z0H3"
enableEmoji = true

[permalinks]
	posts = "/posts/:year-:month-:day/:slug"

[markup.goldmark.renderer]
  unsafe = true

[params]
  logo = "/images/logo.png"
  description = "La MAO pour les noobs."
  #mailchimp = "you can provide a mailchimp-link here, see below"
  #mailprotect = "you can provide a protector-name here, see below"
  #customCSS = ["css/tweaks.css", "css/customHeader.css"]

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]
	page = ["HTML"]


defaultContentLanguage = 'en'
[languages]
  [languages.en]
    title = 'Musical.Studio'
    weight = 1
    contentDir = 'content/en'
    #[languages.en.params]
    #  linkedin = 'https://linkedin.com/whoever'
    #  [languages.en.params.navigation]
    #    help = 'Help'

  [languages.fr]
    title = 'Musical.Studio'
    weight = 2
    contentDir = 'content/fr'
    #[languages.fr.params]
    #  linkedin = 'https://linkedin.com/fr/whoever'
    #  [languages.fr.params.navigation]
    #    help = 'Aide'


[params.author]
  name = "Gilles Chehade"
  thumbnail = "/images/gilles-chehade.jpeg"
  description = "Createur du blog."

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"


## YOUTUBE: https://www.youtube.com/@le.studio.musical